CREATE TABLE salary (id serial PRIMARY KEY,mothly_salary int NOT null);

create table employees (id serial primary key, employee_name varchar (50) not null);

 insert into employees (employee_name)
 values ('Nastya'),
        ('Andrey'),
        ('Katya'),
        ('Tatyana'),
        ('Oleg'),
        ('Yana'),
        ('Olga'),
        ('Irina'),
        ('Petya'),
        ('Svetlana'),
        ('Marina'),
        ('Lilya'),
        ('Dima'),
        ('Valya'),
        ('Kolya'),
        ('Anton'),
        ('Vadim'),
        ('Sasha'),
        ('Alex'),
        ('Oksana'),
        ('Vlad'),
        ('Natalya'),
        ('Igor'),
        ('Milana'),
        ('Valeriya'),
        ('Anna'),
        ('Julia'),
        ('Masha'),
        ('Viktoriya'),
        ('Mario'),
        ('Hanna'),
        ('Roman'),
        ('Nikita'),
        ('Kostya'),
        ('Liza'),
        ('Dariya'),
        ('Vladimir'),
        ('Mikhail'),
        ('Timur'),
        ('Lena'),
        ('Lily'),
        ('Angelina'),
        ('Aleksandra'),
        ('Vera'),
        ('Katerina'),
        ('Galiya'),
        ('Polina'),
        ('Rustem'),
        ('Aleksandr'),
        ('Rinat'),
        ('Uriy'),
        ('Daniil'),
        ('Eleonora'),
        ('Maks'),
        ('Veronika'),
        ('Valeriya'),
        ('Semen'),
        ('Zara'),
        ('Inga'),
        ('Gulya'),
        ('Taisiya'),
        ('Boris'),
        ('Margo'),
        ('Yaroslav'),
        ('Egor'),
        ('Denis'),
        ('Aleksandra'),
        ('Stanislav'),
        ('Nadezhda'),
        ('Elena');
        
   insert into salary (mothly_salary)
   values (1000),
          (1100),
          (1200),
          (1300),
          (1400),
          (1500),
          (1600),
          (1700),
          (1800),
          (1900),
          (2000),
          (2100),
          (2200),
          (2300),
          (2400),
          (2500);
       
         
        ALTER table salary RENAME COLUMN mothly_salary to monthly_salary;
       
       
       create table emloyee_salary(id serial primary key, employee_id int not null unique, salary_id int not null);
      
      alter table emloyee_salary rename to employee_salary;
     
     insert into employee_salary (employee_id, salary_id)
     values (1,5),
     		(3,8),
     		(5,10),
     		(2,9),
     		(4,6),
     		(6,8),
     		(9,10),
     		(8,7),
     		(11,8),
     		(13,1),
     		(10,2),
     		(12,3),
     		(15,12),
     		(16,7),
     		(22,4),
     		(20,12),
     		(25,15),
     		(27,13),
     		(23,1),
     		(28,11),
     		(31,3),
     		(30,2),
     		(45,9),
     		(39,10),
     		(60,14),
     		(55,7),
     		(65,10),
     		(69,15),
     		(70,3),
     		(47,4),
     		(72,11),
     		(121,6),
     		(100,9),
     		(88,10),
     		(113,15),
     		(81,5),
     		(99,2),
     		(118,7),
     		(87,3),
     		(93,10);
     	
     	
     	
     	create table roles (id serial primary key, role_name int not null unique);
     
     alter table roles alter column role_name type varchar(30);
    
     insert into roles (role_name)
     values ('Junior Python developer'),
     		('Middle Python developer'),
     		('Senior Python developer'),
     		('Junior Java developer'),
     		('Middle Java developer'),
     		('Senior Java developer'),
     		('Junior JavaScript developer'),
     		('Middle JavaScript developer'),
     		('Senior JavaScript developer'),
     		('Junior Manual QA engineer'),
     		('Middle Manual QA engineer'),
     		('Senior Manual QA engineer'),
     		('Project Manager'),
     		('Designer'),
     		('HR'),
     		('CEO'),
     		('Sales manager'),
     		('Junior Automation QA engineer'),
     		('Middle Automation QA engineer'),
     		('Senior Automation QA engineer');
     	
     create table roles_employee (
    	 id serial primary key, 
    	 employee_id int not null,
     	foreign key (employee_id) 
    		 references employees (id),
    	 role_id int not null,
     	foreign key (role_id)
   		 	references roles (id)
   		 );
   		
   		insert into roles_employee (employee_id, role_id)
   		values (1,3),
   			   (3,1),
   			   (6,4),
   			   (7,5),
   			   (9,7),
   			   (11,12),
   			   (19,10),
   			   (21,8),
   			   (23,2),
   			   (27,9),
   			   (29,11),
   			   (31,14),
   			   (35,13),
   			   (22,17),
   			   (36,3),
   			   (41,16),
   			   (39,15),
   			   (43,17),
   			   (46,6),
   			   (50,18),
   			   (47,2),
   			   (51,19),
   			   (54,20),
   			   (56,4),
   			   (60,3),
   			   (65,7),
   			   (42,11),
   			   (66,15),
   			   (44,8),
   			   (33,9),
   			   (2,18),
   			   (45,5),
   			   (68,14),
   			   (70,8),
   			   (12,3),
   			   (15,9),
   			   (16,7),
   			   (18,4),
   			   (28,5),
   			   (48,10);
   			
     	
       